# Generated by Django 3.2 on 2022-01-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='order_restaurant', to='foodcartapp.restaurant', verbose_name='Обслуживающий ресторан'),
        ),
    ]
