# Generated by Django 3.2 on 2021-08-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0002_auto_20210609_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmenuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ordersmenuitem',
            name='order',
        ),
        migrations.AddField(
            model_name='ordersmenuitem',
            name='client',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='foodcartapp.orders', verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersmenuitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='foodcartapp.product', verbose_name='Категория товара'),
        ),
    ]
