# Generated by Django 3.2 on 2022-01-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name='Позвонили в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name='Доставлен в'),
        ),
    ]
