# Generated by Django 3.2 on 2021-08-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0004_auto_20210828_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermenuitem',
            old_name='product',
            new_name='products',
        ),
    ]
