# Generated by Django 3.2 on 2022-01-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_alter_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_of_order',
            new_name='status',
        ),
    ]
