# Generated by Django 3.2 on 2022-01-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_auto_20220130_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='total_product_price',
        ),
    ]
