# Generated by Django 3.2 on 2021-08-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_rename_product_ordermenuitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermenuitem',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
