# Generated by Django 3.2 on 2021-11-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_rename_product_quantity_ordermenuitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenuitem',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='foodcartapp.product', verbose_name='Категория товара'),
        ),
    ]
