# Generated by Django 3.2 on 2022-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_rename_product_price_orderitem_total_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
