# Generated by Django 3.2 on 2022-01-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_rename_status_of_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_product',
            new_name='product_price',
        ),
    ]
