# Generated by Django 3.2 on 2021-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0007_alter_ordermenuitem_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenuitem',
            name='price_order_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена товара в заказе с учетом его количества'),
        ),
    ]
