# Generated by Django 3.2 on 2022-01-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0007_rename_price_product_orderitem_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='client',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='foodcartapp.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
