# Generated by Django 3.2 on 2021-11-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0008_ordermenuitem_price_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenuitem',
            name='price_order_item',
        ),
    ]
