# Generated by Django 3.2 on 2022-01-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0008_auto_20220105_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='orders_with_product', to='foodcartapp.product', verbose_name='Категория товара'),
        ),
    ]
