# Generated by Django 3.2 on 2021-11-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0009_remove_ordermenuitem_price_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenuitem',
            name='products',
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='order', to='foodcartapp.Product', verbose_name='Категория товара'),
        ),
    ]
