# Generated by Django 3.2 on 2021-11-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_auto_20211109_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermenuitem',
            name='products',
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='price_per_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена одного товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodcartapp.product', verbose_name='Категория товара'),
        ),
    ]
