# Generated by Django 3.2 on 2021-11-11 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_auto_20211110_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenuitem',
            name='price_per_product',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена одного товара'),
        ),
    ]
