# Generated by Django 3.2 on 2021-11-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0012_alter_ordermenuitem_price_per_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderMenuItem',
            new_name='OrderItem',
        ),
    ]
