# Generated by Django 3.2 on 2021-11-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0013_rename_ordermenuitem_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_product',
        ),
    ]
