# Generated by Django 3.2 on 2021-11-26 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0014_remove_orderitem_price_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена одного товара'),
            preserve_default=False,
        ),
    ]
