# Generated by Django 3.2 on 2021-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0016_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='year_in_school',
            field=models.CharField(choices=[('PR', 'Processed'), ('UNPR', 'Unprocessed')], default='UNPR', max_length=4),
        ),
    ]
