# Generated by Django 3.2 on 2021-11-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0017_order_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='year_in_school',
            new_name='status_of_order',
        ),
    ]
