# Generated by Django 3.2 on 2021-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0018_rename_year_in_school_order_status_of_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
