# Generated by Django 3.2 on 2021-11-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0020_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_of_order',
            field=models.CharField(choices=[('PR', 'Processed'), ('UNPR', 'Unprocessed')], default='UNPR', max_length=4, verbose_name='Статус заказа'),
        ),
    ]
