# Generated by Django 3.2 on 2021-12-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0023_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_restaurant', to='foodcartapp.restaurant', verbose_name='Обслуживаюий ресторан'),
            preserve_default=False,
        ),
    ]
