# Generated by Django 3.2 on 2021-12-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0031_alter_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
    ]
