# Generated by Django 3.2 on 2022-01-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_and_places', '0002_auto_20211221_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='долгота'),
        ),
    ]
